name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 동작

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/folio-backend .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/folio-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Raspberry Pi via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # passphrase: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/folio-backend
          docker stop folio-backend || true
          docker rm folio-backend || true
          docker run -d --name folio-backend -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/folio-backend
          pm2 restart all || pm2 start folio-backend